config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "homes/about"
  resources :users, only: [:show,:index,:edit,:update]
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 has_one_attached :image  
 belongs_to :user, optional: true
 
 
 def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/img/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image
 end
 
 validates :title, presence: true
 validates :body, {presence: true, length: {maximum: 140}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/img/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :name, uniqueness: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?
 protect_from_forgery

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
	 user_path(resource)
  end

  private
  
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def show
    @book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
     else
       @user = current_user
       @books = Book.all
       render :index 
     end
  end  
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        redirect_to book_path(@book.id)
        flash[:notice] = "You have created book successfully."
    else
      render "edit"
    end
  end
  
  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
      @book = Book.find(params[:id])
   unless @book.user == current_user
      redirect_to books_path
   end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <div class="form-group">
    <h1>Editing Book</h1>
    <div>
     <%= flash[:notice] %>
    </div> 

     <h2 class="mt-3">New book</h2> 
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
     <ul>
      <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
      <% end %>
     </ul>
      <% end %>

     <%= form_with model: @book do |f| %>
      <div class="field">
       <%= f.label :Title %></br>
       <%= f.text_field :title, class: "col-xs-12" %>
      </div>

      <div class="form-body">
       <%= f.label :Opinion %></br>
       <%= f.text_area :body, class: "col-xs-12" %>
      </div>

      <div class="actions"></br>
       <%= f.submit 'Updata Book', class: "btn btn-sm btn-success" %>
      </div>
     <% end %>
     
    <div class="menu">
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
    <h2>User Info</h2>
      <table class="table">
       <tbody><tr></tr>
        <tr>
         <th>
          <%= image_tag @user.get_profile_image(100,100) %>
         </th>
        </tr>
	       <th>name</th>
	        <th><%= @user.name %></th>
        </tr>
       <tr>
	       <th>introduction</th>
	      <th></th>
       </tr>
       </tbody>
      </table>
      
      <div class="row">
       <%= link_to edit_user_path(current_user), class:"btn btn-outline-secondary btn-block" do %>
        <span class="fa-solid fa-user-gear" aria-hidden="true"></span>
       <% end %>
      </div>
       
 <h2 class="mt-3">New book</h2> 
  <% if @book.errors.any? %>
   <%= @book.errors.count %>errors prohibited this obj from being saved:
   <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>
 <%= form_with model: @book do |f| %>
  <div class="field">
    <%= f.label :Title %></br>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body">
  	<%= f.label :Opinion %></br>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions"></br>
    <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
  </div>
 <% end %>
</div>
  
  <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
  <table class="table">
   <thead>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
   </thead>
  <tbody>
   <% @books.each do |book| %>
    <tr>
     <td><%= image_tag book.user.get_profile_image(100,100) %></td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body %></td>
    </tr>
   <% end %>
  </tbody>
  </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
	  <h2>User info</h2>
    <table class="table">
     <tbody>
      <tr>
       <th>
        <%= image_tag @user.get_profile_image(100,100) %>
       </th>
       </tr>
       <tr>
	       <th>name</th>
	       <th><%= @user.name %></th>
        </tr>
       <tr>
	       <th>introduction</th>
       </tr>
     </tbody>
    </table>
      
      <div class="container">
       <div class="row">
        <%= link_to edit_user_path(current_user), class:"btn btn-outline-secondary btn-block" do %>
         <span class="fa-solid fa-user-gear" aria-hidden="true"></span>
        <% end %>
       </div>
      </div>

  <h2 class="mt-3">New book</h2>       
 <%= form_with model: @user do |f| %>
  <div class="field">
    <%= f.label :Title %></br>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body">
  	<%= f.label :Opinion %></br>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions"></br>
    <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
  </div>
 <% end %>
</div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tbody>
        <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
         </tr>
        </tbody>
      </table>
    </div>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
 <div class="row">
  <h1 class="px-3 mx-auto">
     welcome to
     <span class="fa-solid fa-book"></span>
     <strong>Bookers</strong>!
  </h1>
 </div>
</div>

app/views/homes/top.html.erb
<div class="container">
<div class="row">
 <div class="mx-auto col-11 col-sm-10- col-lg-8 col-xl-6">
  <h1>welcome to<span class="fa-solid fa-book"></span>
   <strong>Bookers</strong>!!</h1>
    <p>In <span class="fa-solid fa-book"></span><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about varioius books!</p>
    
    <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
     </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/a2b7a944cd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand ">
          <span>Bookers</span>
        </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
          </span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to homes_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
          </ul>
         </div>
      </div>
     </nav>
    </header>
    <div class="body">
      <p class="notice"><%= notice %></p>

      <%= yield %>

       <footer>
        <div class="container mt-5">
         <div class="row">
    	    <div class="mx-auto">
    		   <p>CopyRight Infratop.inc</p>
    	    </div>
         </div>
        </div>
       </footer>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
	  <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
	  <ul>
		<% @user.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
		<% end %>
	  </ul>
	</div>
  <% end %>
<main>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <div class="form-group">
   
<h1>User info</h1>    
 <%= form_with model: @user do |f| %>
   <div class="user-name">Name</div>
    <%= f.text_field :name %>
   <div class="user-edit-image">Image</div>
    <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
   <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %><br>
   <div class="upload">
    <%= f.submit "Update User" %>
   </div>
 <% end %>
</main>
    
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
	  <h2>User info</h2>
      <table class="table">
       <tbody>
        <tr>
         <th>
          <%= image_tag @user.get_profile_image(100,100) %>
         </th>
        </tr>
        <tr>
	        <th>name</th>
	        <th><%= @user.name %></th>
        </tr>
       <tr>
	       <th>introduction</th>
       </tr>
       </tbody>
      </table>
      
      <div class="container">
       <div class="row">
        <%= link_to edit_user_path(current_user), class:"btn btn-outline-secondary btn-block" do %>
         <span class="fa-solid fa-user-gear" aria-hidden="true"></span>
        <% end %>
       </div>
      </div>
      
<div>
  <%= flash[:notice] %>
</div> 

<h2 class="mt-3">New book</h2>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

 <%= form_with model: @book do |f| %>
  <div class="field">
    <%= f.label :Title %></br>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body">
  	<%= f.label :Opinion %></br>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions"></br>
    <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
  </div>
 <% end %>
</div>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
   
    <table class="table">
	    <thead>
	      <th>image</th>
		     <th>name</th>
		     <th colspan="3"></th>
	    </thead>
	    <tbody>
   <% @users.each do |user| %>
    <tr>
     <td><%= image_tag @user.get_profile_image(100,100) %></td>
     <td><%= user.name %></td>
     <td><%= link_to 'Show', user_path(@user.id), method: :get %></td>
    </tr>
   <% end %>
  </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <h2>User info</h2>
    <table class="table">
     <tbody>
      <tr>
       <th>
        <%= image_tag @user.get_profile_image(100,100) %>
       </th>
       </tr>
       <tr>
	       <th>name</th>
	       <th><%= @user.name %></th>
        </tr>
       <tr>
	       <th>introduction</th>
       </tr>
     </tbody>
    </table>
      
      <div class="container">
       <div class="row">
        <%= link_to edit_user_path(current_user), class:"btn btn-outline-secondary btn-block" do %>
         <span class="fa-solid fa-user-gear" aria-hidden="true"></span>
        <% end %>
       </div>
      </div>

<div>
  <%= flash[:notice] %>
</div> 

 <h2 class="mt-3">New book</h2> 
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

 <%= form_with model: @book do |f| %>
  <div class="field">
    <%= f.label :Title %></br>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body">
  	<%= f.label :Opinion %></br>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions"></br>
    <%= f.submit 'Create Book', class: "btn btn-sm btn-success" %>
  </div>
 <% end %>
</div>

  <div class="col-md-8 offset-md-1">
	<h2>Books</h2>
	<!--books一覧 -->
	<table class="table table-hover table-inverse">
  <thead>
	 	<tr>
		  <th></th>
		  <th>Title</th>
		  <th>Opinion</th>
		  <th colspan="3"></th>
	 	</tr>
	 </thead>
	  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
            <%= image_tag @user.get_profile_image(100,100) %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
    <% end %>
  </tbody>
	</table>
	<!--books一覧 -->
  </div>
</div>